---

- name: MYSQL EXPORTER TASK | Ensure that Docker Networks Exist
  docker_network:
    name: "{{ item.name }}"
  with_items: "{{ mysql_exporter_docker_networks }}"

- name: MYSQL EXPORTER TASK | Start Docker Containers [CloudSQL Proxy]
  docker_container:
    name: "{{ item.container_name }}"
    image: "{{ item.image_name }}:{{ item.image_tag }}"
    state: started
    restart_policy: always
    detach: yes
    interactive: yes
    tty: yes
    command: "{{ item.command | default(omit) }}"
    exposed_ports: [ "3306" ]
    ports: "{{ item.ports | default(omit) }}"
    volumes: "{{ item.volumes | default(omit) }}"
    log_driver: "{{ item.log_driver | default(omit) }}"
    network_mode: "{{ item.network_mode | default('bridge') }}"
    networks: "{{ item.networks | default(omit) }}"
    purge_networks: "{{ item.purge_networks | default(omit) }}"
    env: "{{ item.env_vars | default(omit) }}"
  with_items: "{{ cloudsql_proxy_docker_opts }}"
  when: cloudsql_proxy_docker_opts is defined and cloudsql_proxy_docker_opts != ""

- name: MYSQL EXPORTER TASK | Start Docker Containers [MySQL Exporter]
  docker_container:
    name: "{{ item.container_name }}"
    image: "{{ item.image_name }}:{{ item.image_tag }}"
    state: started
    restart_policy: always
    detach: yes
    interactive: yes
    tty: yes
    command: "{{ item.command | default(omit) }}"
    ports: "{{ item.ports | default(omit) }}"
    volumes: "{{ item.volumes | default(omit) }}"
    log_driver: "{{ item.log_driver | default(omit) }}"
    network_mode: "{{ item.network_mode | default('bridge') }}"
    networks: "{{ item.networks | default(omit) }}"
    purge_networks: "{{ item.purge_networks | default(omit) }}"
    env: "{{ item.env_vars | default(omit) }}"
  with_items: "{{ mysql_exporter_docker_opts }}"
  
- name: MYSQL EXPORTER TASK | Add Services to Consul
  uri:
    url: "{{ consul_url }}/v1/agent/service/register"
    method: PUT
    user: "{{ consul_basic_auth_user | default(omit) }}"
    password: "{{ consul_basic_auth_password | default(omit) }}"
    body: "{{ lookup('template', consul_mysql_exporter_docker_template) }}"
    body_format: json
  become: false
  delegate_to: localhost
  when: mysql_exporter_do_not_add_service_to_consul is not defined or (mysql_exporter_do_not_add_service_to_consul is defined and mysql_exporter_do_not_add_service_to_consul == false)
  with_items: "{{ mysql_exporter_docker_opts }}"
