---

- name: NODE EXPORTER TASK | Download Exporter
  get_url:
    url: "{{ node_exporter_tar_url }}"
    dest: "/tmp/node_exporter.tar.gz"
    mode: "0644"

- name: NODE EXPORTER TASK | Extract Archive
  unarchive:
    src: "/tmp/node_exporter.tar.gz"
    dest: "/usr/sbin"
    remote_src: true
    extra_opts:
    - "--strip-components=1"
    - "--wildcards"
    - "*/node_exporter"
  register: binary

- name: NODE EXPORTER TASK | Ensure that the Log Directory Exists
  file:
    path: "/var/log/node_exporter"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: NODE EXPORTER TASK | Ensure that Systemd Service Exists
  template:
    src: "{{ node_exporter_systemd_config }}"
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: "0644"
  register: service
  when: ansible_service_mgr == "systemd"

- name: NODE EXPORTER TASK | Enable 'node_exporter' Service
  systemd:
    daemon_reload: yes
    name: node_exporter
    enabled: yes
    state: restarted
  when: binary.changed or service.changed

- name: NODE EXPORTER TASK | Ensure that Initd Service Exists
  template:
    src: "{{ node_exporter_initd_config }}"
    dest: /etc/init.d/node_exporter
    owner: root
    group: root
    mode: "0644"
  register: service
  when: ansible_service_mgr != "systemd"

- name: NODE EXPORTER TASK | Restart the Initd Service
  service:
    name: node_exporter
    state: restarted
  when: (ansible_service_mgr != "systemd" and binary.changed) or (ansible_service_mgr != "systemd" and service.changed)

- name: NODE EXPORTER TASK | Add Binary Path to the Textfile Collector Cron Job File
  cronvar:
    name: "PATH"
    value: "/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/snap/bin"
    cron_file: "node_exporter_textfile_collector"
  when: node_textfile_collector_cron_jobs is defined and node_textfile_collector_cron_jobs != ""

- name: NODE EXPORTER TASK | Ensure that the Textfile Collector Directory Exists
  file:
    path: "{{ node_textfile_collector_directory }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  when: (node_textfile_collector_directory is defined and node_textfile_collector_directory != "") and (node_textfile_collector_cron_jobs is defined and node_textfile_collector_cron_jobs != "")

- name: NODE EXPORTER TASK | Configure Cron Jobs for the Textfile Collector
  cron:
    name: "{{ item.cron_name }}"
    cron_file: node_exporter_textfile_collector
    job: "{{ item.cron_command }}"
    user: root
    hour: "{{ item.cron_hour }}"
    minute: "{{ item.cron_minute }}"
    weekday: "{{ item.day_of_week }}"
    day: "{{ item.day_of_month }}"
  with_items: "{{ node_textfile_collector_cron_jobs }}"
  when: node_textfile_collector_cron_jobs is defined and node_textfile_collector_cron_jobs != ""

- name: NODE EXPORTER TASK | Add Services to Consul
  uri:
    url: "{{ consul_url }}/v1/agent/service/register"
    method: PUT
    user: "{{ consul_basic_auth_user | default(omit) }}"
    password: "{{ consul_basic_auth_password | default(omit) }}"
    body: "{{ lookup('template', consul_node_exporter_template) }}"
    body_format: json
  become: false
  delegate_to: localhost
  when: node_exporter_do_not_add_service_to_consul is not defined or (node_exporter_do_not_add_service_to_consul is defined and node_exporter_do_not_add_service_to_consul == false)
