---

- name: PUSHGATEWAY DOCKER TASK | Start Docker Containers
  docker_container:
    name: "{{ item.container_name }}"
    image: "{{ item.image_name }}:{{ item.image_tag }}"
    state: started
    restart_policy: always
    detach: yes
    interactive: yes
    tty: yes
    command: "{{ item.command | default(omit) }}"
    ports: "{{ item.ports | default(omit) }}"
    volumes: "{{ item.volumes | default(omit) }}"
    log_driver: "{{ item.log_driver | default(omit) }}"
    network_mode: "{{ item.network_mode | default('bridge') }}"
    networks: "{{ item.networks | default(omit) }}"
    purge_networks: "{{ item.purge_networks | default(omit) }}"
    env: "{{ item.env_vars | default(omit) }}"
  with_items: "{{ pushgateway_docker_opts }}"

- name: PUSHGATEWAY DOCKER TASK | Add Services to Consul
  uri:
    url: "{{ consul_url }}/v1/agent/service/register"
    method: PUT
    user: "{{ consul_basic_auth_user | default(omit) }}"
    password: "{{ consul_basic_auth_password | default(omit) }}"
    body: "{{ lookup('template', consul_pushgateway_template) }}"
    body_format: json
  become: false
  delegate_to: localhost
  when: pushgateway_do_not_add_service_to_consul is not defined or (pushgateway_do_not_add_service_to_consul is defined and pushgateway_do_not_add_service_to_consul == false)
